### ISSUE TITLE
FIX no longer works

### ISSUE THREAD

**Issue by allanlaal** [clux/yr-cli#3]
allan@S5:/opt/yr-cli.clux$ ./bin.js 
	/opt/yr-cli.clux/lib/index.js:61
	        location.getForecastForTime(time, cleanUpData);
	                 ^
	
	TypeError: Cannot read properties of null (reading 'getForecastForTime')
	    at /opt/yr-cli.clux/lib/index.js:61:18
	    at /opt/yr-cli.clux/node_modules/.pnpm/yr.no-forecast@0.0.7/node_modules/yr.no-forecast/index.js:232:14
	    at Request._callback (/opt/yr-cli.clux/node_modules/.pnpm/yr.no-interface@0.1.1/node_modules/yr.no-interface/lib/apiRequest.js:33:14)
	    at self.callback (/opt/yr-cli.clux/node_modules/.pnpm/request@2.25.0/node_modules/request/index.js:148:22)
	    at Request.emit (node:events:511:28)
	    at self.clientErrorHandler (/opt/yr-cli.clux/node_modules/.pnpm/request@2.25.0/node_modules/request/index.js:257:10)
	    at ClientRequest.emit (node:events:511:28)
	    at Socket.socketErrorListener (node:_http_client:495:9)
	    at Socket.emit (node:events:511:28)

**Comment by clux** [comment]
I presume we need to update the underlying `yr.no-forecast` library. Have not really tried this library in ages, but will take a PR to update it.
